// Copyright (C) 2015 BK

#ifndef MLINTERPOLATION_INTERPOLATIONTYPES_H_
#define MLINTERPOLATION_INTERPOLATIONTYPES_H_

namespace ML {

enum G_NOISY_BOUNDARY_TYPE { G_BOUND_NONE = 0, G_BOUND_C1, G_BOUND_C2 };

}  // namespace ML

#endif  // MLINTERPOLATION_INTERPOLATIONTYPES_H_
